CREATE USER C##doublev IDENTIFIED BY doublev
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP";

GRANT CONNECT, RESOURCE TO C##doublev; 
GRANT CREATE PUBLIC SYNONYM TO C##doublev;
GRANT DROP PUBLIC SYNONYM TO C##doublev;